const body = document.querySelector('body')
console.log(body)
const header = document.querySelector('header')
console.log(header)
const footer = document.querySelector('footer')
console.log(footer)
const toggleBackgroundButton = document.querySelector('.toggle-background')
console.log(toggleBackgroundButton)
const weather = document.querySelector('.weather')
console.log(weather)
const elements = document.querySelectorAll('.background-blue')
console.log(elements)